#!/bin/bash
CMD[0]="checkHistory \"pwd\""
CMD[1]="checkHistory \"cd ..\""
CMD[2]="checkHistory \"cd target\""
CMD[3]="checkHistory \"cd ../..\""
CMD[4]="checkHistory \"cd ~\""
CMD[5]="checkHistory \"cd /\""
CMD[6]="checkHistory \"ls -l -h\""
CMD[7]="checkHistory \"ls /usr/lib\""
CMD[8]="checkHistory \"ls -l -h /lib/x86_64-linux-gnu/\""
CMD[9]="checkHistory \"dpkg-maintscript-helper\""
CMD[10]="checkHistory \"df -h\""
CMD[11]="checkHistory \"ls --help\""
CMD[12]="checkHistory \"exit\""
